language: java
install: true
sudo: false

os: linux
dist: trusty
jdk: oraclejdk8

before_script:
  - chmod +x gradlew
  - ls -la build
  - ls -la build/reports

script:
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew jacocoTestReport

# From https://github.com/DiscordHooks/travis-ci-discord-webhook
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
