language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - chmod +x gradlew
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

# From https://github.com/DiscordHooks/travis-ci-discord-webhook
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
