comments:
  AbsentOrWrongFileLicense:
    active: true
    licenseTemplateFile: "license.template"
  EndOfSentenceFormat:
    active: true
    endOfSentenceFormat: "([.?!][ \t\n\r\f<])|([.?!:]$)"
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

complexity:
  StringLiteralDuplication:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: "$^"

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: [toString, hashCode, equals, finalize]
  InstanceOfCheckForException:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - InterruptedException
      - NumberFormatException
      - ParseException
      - MalformedURLException
      allowedExceptionNameRegex: "_|(ignore|expected).*"
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions:
      - IllegalArgumentException
      - IllegalStateException
      - IOException
  ThrowingNewInstanceOfSameException:
    active: true

formatting:
  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true
  EnumEntryNameCase:
    active: true
    autoCorrect: true
  ImportOrdering:
    active: true
    autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true

naming:
  InvalidPackageDeclaration:
    active: true
    rootPackage: ""
  VariableMaxLength:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
    maximumVariableNameLength: 64
  VariableMinLength:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
    minimumVariableNameLength: 3
  VariableNaming:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
    variablePattern: "[a-z][A-Za-z0-9]*"
    privateVariablePattern: "_[a-z][A-Za-z]*"
    excludeClassPattern: "$^"
    ignoreOverridden: true

potential-bugs:
  HasPlatformType:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UselessPostfixExpression:
    active: true

style:
  active: true
  CollapsibleIfStatements:
    active: true
  DataClassShouldBeImmutable:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: false
  ForbiddenMethodCall:
    active: true
    methods: []
  ForbiddenVoid:
    active: true
    ignoreOverriden: false
    ignoreUsageInGenerics: false
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  NestedClassesVisibility:
    active: true
  NoTabs:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableDecimalLength: 5
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: "(_|ignored|expected|serialVersionUID)"
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckOrError:
    active: true
  UseRequire:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
    excludes: []
    excludeImports: []
